### ISSUE TITLE
注册失败啊

### ISSUE THREAD

**Issue by wangya123456789** [shizq123/BIKA#1]

**Comment by shizq123** [comment]
你好，有没有错误信息截图？

**Comment by shizq123** [comment]
你好，有没有错误信息截图？

**Comment by wangya123456789** [comment]
注册失败  网络错误code=400 error=1008message=email is already exist

有个疑问，我看你那个怎么还调用接口呢？是你个人的接口吗？你不是利用[tachiyomi](https://github.com/tachiyomiorg/tachiyomi)的扩展制作的？

**Comment by shizq123** [comment]
email is already exist 是邮箱注册过了。这个不是tachiyomi的扩展制作，我是自己抓包抓的接口做的第三方app，能力有限功能还不完善
