### ISSUE TITLE
封印的选项可以记住

### ISSUE THREAD

**Issue by zyp997** [shizq123/BIKA#13]
每次点开其它栏目，封印都需要重新点击。

**Comment by dongkid** [comment]
同意，这是一个非常缺失的功能。

**Comment by shizq123** [comment]
抱歉，没时间更新，这个项目我鸽了

**Comment by niuhuan** [comment]
已改进并提PR

**Comment by shizq123** [comment]
> 已改进并提PR

感谢

**Comment by dongkid** [comment]
> 已改进并提PR

感谢

**Comment by dongkid** [comment]
> > 已改进并提PR
> 
> 感谢

作者发版吧

**Comment by niuhuan** [comment]
你如果着急的话可以去逛逛我的仓库 flutter yyds @dongkid

**Comment by shizq123** [comment]
> > > 已改进并提PR
> > 
> > 
> > 感谢
> 
> 作者发版吧

抱歉，我确实没时间，推荐使用这位大佬仓库的项目，或者其他第三方应用

**Comment by shizq123** [comment]
closed by [Release v1.0.6](https://github.com/shizq123/BIKA/releases/tag/v1.0.6).
