### ISSUE TITLE
作者大大如果有空的话可以优先更新下载功能吗？

### ISSUE THREAD

**Issue by Runninginsilence1** [shizq123/BIKA#15]
本人也是安卓小白一枚，正在研究您的源码...
不过个人平时用bika也只是用来下漫画和本子看的，作者大大要增加新功能的话可以考虑先更新下载功能吗？
只是我个人的意愿！不用更新也可以的！

**Comment by shizq123** [comment]
你说的更新下载什么意思，app里有内置版本检测更新

**Comment by shizq123** [comment]
好吧，我的问题，我断句看错了，你说的是加个下载功能对吧 :)

**Comment by shizq123** [comment]
这个项目我没时间更新，github上有很多比我这个项目优秀的第三方哔咔，需要下载的话推荐使用其他第三方的哔咔，非常抱歉，可以查看我的stars找到其他第三方哔咔
