### ISSUE TITLE
网络错误，卡在检查账号信息

### ISSUE THREAD

**Issue by Mr-233333** [shizq123/BIKA#20]
网络连接正常，使用哔咔官方APP可以正常浏览
卡在检查账号信息，在历史记录里点开就报网络错误
![IMG_20240322_210525](https://github.com/shizq123/BIKA/assets/116350991/54dd0ad6-d44b-4109-bc92-b710c41fa8f4)
![IMG_20240322_210516](https://github.com/shizq123/BIKA/assets/116350991/22a032d8-3148-42c2-8678-e5638e9f9b53)

**Comment by shizq123** [comment]
已修复 新版本[v1.0.7](https://github.com/shizq123/BIKA/releases/tag/v1.0.7)
