### ISSUE TITLE
关于阅读建议

### ISSUE THREAD

**Issue by xyzk903** [shizq123/BIKA#22]
阅读时自动隐藏手机的状态栏，app的标题栏，并且在滑动阅读的同时也会自动隐藏，达到一个阅读过程中屏幕只有漫画内容的效果，这样能大幅提升阅读体验。单击屏幕时，在屏幕底部显示阅读页数并且提供可以左右滑动来翻页的进度条，这样会方便不少

**Comment by shizq123** [comment]
感谢支持 能力有限 阅读功能还没有写
