### ISSUE TITLE
能否在使用代理时，运行BIKA？

### ISSUE THREAD

**Issue by youlan2333** [shizq123/BIKA#26]

**Comment by youlan2333** [comment]
经测试使用流量，流量apn代理，wifi代理都不能加载，只有走wifi才可以加载![Screenshot_20240730-143350.png](https://github.com/user-attachments/assets/0a71e87d-ef09-4cda-a396-1d2336418e31)

**Comment by shizq123** [comment]
不懂 应该不能用吧

**Comment by youlan2333** [comment]
> 不懂 应该不能用吧

而事实是，开了代理进不去:⁠ (

**Comment by Cynthia0329** [comment]
> > 不懂 应该不能用吧
> 
> 而事实是，开了代理进不去:⁠ (

我一直以为就我有这个问题……包括原版哔咔的app也是这样😂（老平板就没这个问题，这两年的新手机都这样）

**Comment by shizq123** [comment]
哔咔在高峰期会连不上，我都是白天裸连抓包测试，代理这东西不是很懂，这个项目暂时不更新，我准备换项目架构，还在学习中，还有我用V2ray，启用的虚拟DNS正常使用
![微信图片_20240808235703](https://github.com/user-attachments/assets/5e9c1c4d-0bb3-4e3a-90dd-c21945328d4f)
