### ISSUE TITLE
请求添加跳转第几页的功能

### ISSUE THREAD

**Issue by Vemon233** [shizq123/BIKA#4]
感谢大佬的分享，请问是否考虑跳转到具体页面的功能呢，谢谢

**Comment by shizq123** [comment]
ok没问题

**Comment by Vemon233** [comment]
感谢大佬

**Comment by Vemon233** [comment]
> ok没问题

突然感觉自己好像没有说清楚可能会有歧义
我希望的是能够跳转到收藏夹的第几页
当然能跳转到漫画的第几页也是很不错的，谢谢

**Comment by shizq123** [comment]
漫画的跳转还没写，只写了列表的页数包括收藏，评论的页数也没写（我比较懒）

**Comment by shizq123** [comment]
![Screenshot_20230131_124848](https://user-images.githubusercontent.com/28527363/215668134-8d1c29ea-f356-4775-9de2-f4cee05c82f4.png)

**Comment by shizq123** [comment]
![Screenshot_20230131_124848](https://user-images.githubusercontent.com/28527363/215668548-56c783ba-47be-4e13-82b2-33e004e7c59f.png)

**Comment by Vemon233** [comment]
好的，感谢大佬，抽空弄不弄的都行，也不是非常需要这个功能，只是建议有

**Comment by shizq123** [comment]
新版本更新
