### ISSUE TITLE
添加图标

### ISSUE THREAD

**Issue by ODtian** [shizq123/BIKA#5]
可以参考md3版本的ehviewer![Screenshot_20230125-211913_Evolution_X_Launcher.png](https://user-images.githubusercontent.com/40318251/214573676-8891e201-ebcb-4316-a7fb-3095ecd60fe7.png)

**Comment by shizq123** [comment]
我不会设计，下个版本会有新图标，https://github.com/shizq123/BIKA/blob/master/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png

**Comment by ODtian** [comment]
期待更新，但是md3不支持主题图标有些可惜

**Comment by shizq123** [comment]
![image](https://user-images.githubusercontent.com/28527363/214821895-62739d65-077a-4158-9c71-544cd1152ad4.png)
你说的是这种吗，Android13的带主题图标吗

**Comment by shizq123** [comment]
![image](https://user-images.githubusercontent.com/28527363/214825234-24aedfff-b3c4-4287-8a1e-98ca80808cdf.png)
最终效果是这样的

**Comment by ODtian** [comment]
感谢，看起来舒服了
