### ISSUE TITLE
挂不上代理？

### ISSUE THREAD

**Issue by Smile8848** [shizq123/BIKA#6]
![MX {%VKSVN`E69R00WZMTH2](https://user-images.githubusercontent.com/31927778/216241529-9f7da07c-a54b-4926-bc0c-037e6b35a4a8.jpg)
也不知道为啥界面都进不去

**Comment by Smile8848** [comment]
我去怎么能直连。。。挂vpn反而寄了。

**Comment by shizq123** [comment]
那可能vpn问题 我V2ray没问题，clash要进主页后开启，其实现在大部分时间可以不用vpn也能进

**Comment by shizq123** [comment]
你显示这个页面不挂v也能进

**Comment by Smile8848** [comment]
![FU~R4JQ%82)YN@MN63{U5FB](https://user-images.githubusercontent.com/31927778/216243524-281572e0-8e72-4780-8ba6-413775459587.jpg)
![XKHC2EOEP)6DAR 58VRHW3P](https://user-images.githubusercontent.com/31927778/216243529-7db0dd45-b2aa-4994-880a-2e6bf32f8745.jpg)
应该不是梯子问题 因为用立柜是能正常访问，很迷，不挂vpn主要加载真的急死。。。

**Comment by shizq123** [comment]
https://user-images.githubusercontent.com/28527363/216244614-ac1c21e6-de31-4bdd-82cf-99481ccdd355.mp4

**Comment by Smile8848** [comment]
> 1675317702281.mp4

是这样的0.0 姑且这么用着吧。

**Comment by shizq123** [comment]
https://user-images.githubusercontent.com/28527363/216244843-e91dbdcd-be83-4f37-ae1d-ccb70ef89f09.mp4

**Comment by shizq123** [comment]
发送的视频好像播放不显示，这个bug后面修复

**Comment by Smile8848** [comment]
不过大佬能加个一键复制[画师名]+本子名的吗

**Comment by shizq123** [comment]
长按复制

**Comment by Smile8848** [comment]
> 长按复制

是想能一键复制画师名加上本子名的那种， 貌似这个长按的需要-长按-全选-复制，跟原版的哔咔一个逻辑
没有打算开发也没事0.0..

**Comment by shizq123** [comment]
可以考虑

**Comment by Smile8848** [comment]
> 可以考虑

感谢

**Comment by shizq123** [comment]
![image](https://user-images.githubusercontent.com/28527363/216273421-594a842f-7219-403e-85ad-e8500d828a8c.png)

**Comment by shizq123** [comment]
抱歉不是这个问题

**Comment by shizq123** [comment]
![image](https://user-images.githubusercontent.com/28527363/216280073-3227315d-983d-43b7-b39a-3d939a6c25e5.png)
clash 关闭系统代理解决

**Comment by Smile8848** [comment]
> 抱歉 没解决 电脑wsa上正常，谷歌哔咔都可以，到手机哔咔上不去 推荐你换V2ray吧

买的梯子没有v2订阅。。我按这个弄了倒是能正常访问

**Comment by shizq123** [comment]
> 

好使好使，我手机上好久没更新节点的问题，还是代理模式，谷歌可以上去，哔咔也可以
