### ISSUE TITLE
蓝奏

### ISSUE THREAD

**Issue by buiawpkgew1** [shizq123/BIKA#8]
可以用蓝奏云解析[API](https://res.abeim.cn/api/lanzou_jx/doc.html)地址

**Comment by shizq123** [comment]
我不会 哈哈 蓝奏的下载地址好像经常变

**Comment by shizq123** [comment]
我是看蓝云app用的appcenter，挺好用，还提供了api

**Comment by shizq123** [comment]
> 可以用蓝奏云解析[API](https://res.abeim.cn/api/lanzou_jx/doc.html)地址

获取链接失败 不行 这只是提供下载地址的不能用于检测版本更新
